=== phrase/openapi/webhook_schemas/branches_sync.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "gravatar_uid": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "main_format": {
          "type": "string"
        },
        "project_image_url": {
          "type": "null"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "point_of_contact": {
          "type": "null"
        }
      },
      "required": [
        "id",
        "name",
        "slug",
        "main_format",
        "project_image_url",
        "created_at",
        "updated_at",
        "point_of_contact"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "base_project_id": {
          "type": "string"
        },
        "branch_project_id": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "merged_at": {
          "type": "null"
        },
        "state": {
          "type": "string"
        },
        "child_branches": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "created_by": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "gravatar_uid": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "username",
            "name",
            "gravatar_uid"
          ]
        },
        "merged_by": {
          "type": "null"
        }
      },
      "required": [
        "name",
        "base_project_id",
        "branch_project_id",
        "created_at",
        "updated_at",
        "merged_at",
        "state",
        "child_branches",
        "created_by",
        "merged_by"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "sent_at",
    "user",
    "project",
    "branch"
  ]
}

=== phrase/openapi/webhook_schemas/branches_sync_example.json
{
  "event": "branches:sync",
  "message": "john.smith synced branch new-feature-2 in project Translation Project",
  "sent_at": "2025-10-24 07:17:50 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-2",
    "base_project_id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "branch_project_id": "8228978fc13f5eb3c4cbbe8ac9882b64",
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-10-24 07:17:49 UTC",
    "merged_at": null,
    "state": "initialized",
    "child_branches": [
      "child-branch-1"
    ],
    "created_by": {
      "id": "24b9a53ad72e198ca332fba91bb95f57",
      "username": "john.smith",
      "name": "John Smith",
      "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
    },
    "merged_by": null
  }
}
