=== phrase/openapi/webhook_schemas/comments_create.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "gravatar_uid": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "main_format": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "main_format",
        "created_at",
        "updated_at"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "comment": {
      "type": "object",
      "title": "comment",
      "properties": {
        "id": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "user": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": [
                "string",
                "null"
              ]
            },
            "gravatar_uid": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "username",
            "name",
            "gravatar_uid"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "mentioned_users": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "username": {
                "type": "string"
              },
              "name": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "gravatar_uid": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "id",
              "username",
              "name",
              "gravatar_uid"
            ]
          }
        },
        "key": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": [
                "string",
                "null"
              ]
            },
            "name_hash": {
              "type": [
                "string",
                "null"
              ]
            },
            "plural": {
              "type": "boolean"
            },
            "max_characters_allowed": {
              "type": [
                "integer",
                "null"
              ]
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "created_at": {
              "type": "string",
              "format": "date-time"
            },
            "updated_at": {
              "type": "string",
              "format": "date-time"
            }
          },
          "required": [
            "id",
            "name",
            "description",
            "name_hash",
            "plural",
            "max_characters_allowed",
            "tags",
            "created_at",
            "updated_at"
          ]
        }
      },
      "required": [
        "id",
        "message",
        "user",
        "created_at",
        "updated_at",
        "mentioned_users"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project"
  ]
}

=== phrase/openapi/webhook_schemas/comments_create_example.json
{
  "event": "comments:create",
  "message": "john.smith commented on job \"Job 1\" in project Translation Project within branch new-feature-1",
  "sent_at": "2025-02-07 16:44:04 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "comment": {
    "id": "68740d06f87390fd357f12e0d7ddb9a2",
    "message": "Job is looking ready to go",
    "has_replies": false,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "user": {
      "id": "24b9a53ad72e198ca332fba91bb95f57",
      "username": "john.smith",
      "name": "John Smith",
      "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
    },
    "mentioned_users": [],
    "locales": []
  }
}
