=== phrase/openapi/webhook_schemas/custom_metadata_values_update.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "gravatar_uid": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "main_format": {
          "type": "string"
        },
        "project_image_url": {
          "type": "null"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "point_of_contact": {
          "type": "null"
        }
      },
      "required": [
        "id",
        "name",
        "slug",
        "main_format",
        "project_image_url",
        "created_at",
        "updated_at",
        "point_of_contact"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "custom_metadata_value": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "value"
      ]
    },
    "key": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "plural": {
          "type": "boolean"
        },
        "data_type": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "id",
        "name",
        "plural",
        "data_type",
        "tags"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "branch",
    "custom_metadata_value",
    "key"
  ]
}

=== phrase/openapi/webhook_schemas/custom_metadata_values_update_example.json
{
  "event": "custom_metadata_values:update",
  "message": "john.smith updated custom metadata value Platform for key application.modal.header in project Translation Project within branch new-feature-1",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "custom_metadata_value": {
    "id": "2e7d22d447a0941ea534b09176da7b83",
    "name": "Platform",
    "value": "Android"
  },
  "key": {
    "id": "fe5b97045d80f91dd950b695d5ebe607",
    "name": "application.modal.header",
    "plural": false,
    "data_type": "string",
    "tags": [
      "web"
    ]
  }
}
