=== phrase/openapi/webhook_schemas/keys_tags_batch_create.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string",
      "enum": ["keys:tags:batch_create"]
    },
    "message": { "type": "string" },
    "sent_at": {
      "anyOf": [
        { "type": "string", "format": "date-time" },
        { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} UTC$" }
      ]
    },
    "user": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "username": { "type": "string" },
        "name": { "type": ["string", "null"] },
        "gravatar_uid": { "type": ["string", "null"] }
      },
      "required": ["id", "username", "name", "gravatar_uid"]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "name": { "type": "string" },
        "slug": { "type": "string" },
        "main_format": { "type": ["string", "null"] },
        "project_image_url": { "type": ["string", "null"], "format": "uri" },
        "created_at": {
          "anyOf": [
            { "type": "string", "format": "date-time" },
            { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} UTC$" }
          ]
        },
        "updated_at": {
          "anyOf": [
            { "type": "string", "format": "date-time" },
            { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} UTC$" }
          ]
        },
        "point_of_contact": {
          "type": ["object", "null"],
          "properties": {
            "id": { "type": "string" },
            "username": { "type": "string" },
            "name": { "type": ["string", "null"] },
            "gravatar_uid": { "type": ["string", "null"] }
          },
          "required": ["id", "username", "name", "gravatar_uid"]
        }
      },
      "required": ["id", "name", "main_format", "created_at", "updated_at"]
    },
    "branch": {
      "type": ["object", "null"],
      "properties": {
        "name": { "type": "string" }
      },
      "required": ["name"]
    },
    "keys": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "tags": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": { "type": "string" }
              },
              "required": ["name"]
            }
          }
        },
        "required": ["id", "tags"]
      }
    }
  },
  "required": ["event", "message", "sent_at", "user", "project", "keys"]
}

=== phrase/openapi/webhook_schemas/keys_tags_batch_create_example.json
{
  "event": "keys:tags:batch_create",
  "message": "john.smith tagged 1 key in project Translation Project within branch new-feature-1",
  "sent_at": "2025-08-17 14:59:05 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "keys": [
    {
      "id": "fe5b97045d80f91dd950b695d5ebe607",
      "tags": [
        {
          "name": "web"
        }
      ]
    }
  ]
}
