=== phrase/openapi/webhook_schemas/project_update.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "const": "project:update"
    },
    "message": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "gravatar_uid": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": [
            "string",
            "null"
          ]
        },
        "main_format": {
          "type": [
            "string",
            "null"
          ]
        },
        "project_image_url": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "account": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "slug": {
              "type": [
                "string",
                "null"
              ]
            },
            "company": {
              "type": [
                "string",
                "null"
              ]
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            },
            "company_logo_url": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "name",
            "slug",
            "company",
            "created_at",
            "updated_at",
            "company_logo_url"
          ]
        },
        "space": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "slug": {
              "type": "string"
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            },
            "projects_count": {
              "type": "number"
            }
          },
          "required": [
            "id",
            "name",
            "slug",
            "created_at",
            "updated_at",
            "projects_count"
          ]
        },
        "point_of_contact": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": [
                "string",
                "null"
              ]
            },
            "gravatar_uid": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "username",
            "name",
            "gravatar_uid"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "slug",
        "main_format",
        "project_image_url",
        "created_at",
        "updated_at",
        "account",
        "space",
        "point_of_contact"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project"
  ]
}

=== phrase/openapi/webhook_schemas/project_update_example.json
{
  "event": "project:update",
  "message": "john.smith updated project Translation Project",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "account": {
      "id": "abcdef1",
      "name": "Company account",
      "slug": "company-account",
      "company": "Pawtucket Brewery",
      "created_at": "2025-02-07 16:18:13 UTC",
      "updated_at": "2025-02-07 16:44:04 UTC",
      "company_logo_url": null
    },
    "space": null,
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  }
}
