=== phrase/openapi/webhook_schemas/releases_create.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "user": {
      "$ref": "user.json"
    },
    "project": {
      "$ref": "project.json"
    },
    "branch": {
      "$ref": "branch.json"
    },
    "release": {
      "$ref": "release.json"
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "branch",
    "release"
  ]
}

=== phrase/openapi/webhook_schemas/releases_delete_example.json
{
  "event": "releases:delete",
  "message": "john.smith deleted a release 48 in distribution Android Distribution in project Translation Project",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "release": {
    "id": "97f8be200b23fa28f05bfcddfcb75869",
    "version": 12,
    "app_min_version": "1.0.0",
    "app_max_version": "2.0.0",
    "description": null,
    "platforms": [
      "android",
      "ios"
    ],
    "environments": [
      "development",
      "production"
    ],
    "locale_codes": [
      "en"
    ],
    "tags": [],
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC"
  }
}
