=== phrase/openapi/webhook_schemas/screenshots_create.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "gravatar_uid": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "main_format": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "main_format",
        "created_at",
        "updated_at"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "screenshot": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "screenshot_url": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "markers_count": {
          "type": "integer"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "screenshot_url",
        "created_at",
        "updated_at",
        "markers_count"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "screenshot"
  ]
}

=== phrase/openapi/webhook_schemas/screenshots_update_example.json
{
  "event": "screenshots:update",
  "message": "john.smith updated screenshot main_view_screenshot in project Translation Project within branch new-feature-1",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "screenshot": {
    "id": "b827204f17cefe7fa3b6a8ced17ead26",
    "name": "main_view_screenshot",
    "description": "Showing the main screen",
    "screenshot_url": "http://www.example.com/uploads/screenshots/b827204f17cefe7fa3b6a8ced17ead26/screenshot-7411f4f0a5c11802.jpg",
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "markers_count": 0
  }
}
