=== phrase/openapi/webhook_schemas/translations_batch_include.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "gravatar_uid": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "email",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "main_format": {
          "type": "string"
        },
        "project_image_url": {
          "type": "null"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "point_of_contact": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": [
                "string",
                "null"
              ]
            },
            "gravatar_uid": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      },
      "required": [
        "id",
        "name",
        "slug",
        "main_format",
        "project_image_url",
        "created_at",
        "updated_at",
        "point_of_contact"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "translations": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "content": {
              "type": "string"
            },
            "unverified": {
              "type": "boolean"
            },
            "excluded": {
              "type": "boolean"
            },
            "plural_suffix": {
              "type": "string"
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            },
            "placeholders": {
              "type": "array",
              "items": {}
            },
            "state": {
              "type": "string"
            },
            "key": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "plural": {
                  "type": "boolean"
                },
                "data_type": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": {}
                }
              },
              "required": [
                "id",
                "name",
                "plural",
                "data_type",
                "tags"
              ]
            },
            "locale": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "code": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "name",
                "code"
              ]
            }
          },
          "required": [
            "id",
            "content",
            "unverified",
            "excluded",
            "plural_suffix",
            "created_at",
            "updated_at",
            "placeholders",
            "state",
            "key",
            "locale"
          ]
        }
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "branch",
    "translations"
  ]
}

=== phrase/openapi/webhook_schemas/translations_batch_include_example.json
{
  "event": "translations:batch_include",
  "message": "1 translations included in project Translation Project within branch new-feature-1",
  "sent_at": "2025-08-07 13:44:50 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "email": "john.smith@example.com",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "translations": [
    {
      "id": "89252e4570e73c051fce446c8c55670d",
      "content": "Header title",
      "unverified": false,
      "excluded": false,
      "plural_suffix": "",
      "created_at": "2025-02-07T16:18:13Z",
      "updated_at": "2025-02-07T16:18:13Z",
      "placeholders": [],
      "state": "translated",
      "key": {
        "id": "fe5b97045d80f91dd950b695d5ebe607",
        "name": "application.modal.header",
        "plural": false,
        "use_ordinal_rules": false,
        "data_type": "string",
        "tags": [
          "web"
        ]
      },
      "locale": {
        "id": "7d8614f35033cebada71d4471fd87518",
        "name": "en",
        "code": "en"
      }
    }
  ]
}
